export const teamFlags = {
  Alemania: "🇩🇪",
  "Arabia Saudita": "🇸🇦",
  Argelia: "🇩🇿",
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Belgica: "🇧🇪",
  "Bosnia y Herzegovina": "🇧🇦",
  Brasil: "🇧🇷",
  "Cabo Verde": "🇨🇻",
  Canada: "🇨🇦",
  Catar: "🇶🇦",
  Chequia: "🇨🇿",
  Colombia: "🇨🇴",
  "Corea del Sur": "🇰🇷",
  "Costa de Marfil": "🇨🇮",
  Croacia: "🇭🇷",
  Curazao: "🇨🇼",
  Ecuador: "🇪🇨",
  Egipto: "🇪🇬",
  Escocia: "🏴",
  Espana: "🇪🇸",
  "Estados Unidos": "🇺🇸",
  Francia: "🇫🇷",
  Ghana: "🇬🇭",
  Haiti: "🇭🇹",
  Inglaterra: "🏴",
  Irak: "🇮🇶",
  Iran: "🇮🇷",
  Japon: "🇯🇵",
  Jordania: "🇯🇴",
  Marruecos: "🇲🇦",
  Mexico: "🇲🇽",
  Noruega: "🇳🇴",
  "Nueva Zelanda": "🇳🇿",
  "Paises Bajos": "🇳🇱",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  Portugal: "🇵🇹",
  "RD Congo": "🇨🇩",
  Senegal: "🇸🇳",
  Sudafrica: "🇿🇦",
  Suecia: "🇸🇪",
  Suiza: "🇨🇭",
  Tunez: "🇹🇳",
  Turquia: "🇹🇷",
  Uruguay: "🇺🇾",
  Uzbekistan: "🇺🇿"
};

export function flagForTeam(team) {
  return teamFlags[team] || "🏳️";
}
